.PHONY: run clean

run:
	c++ -O2 -std=c++17 recurrence_resource_model.cpp -o recurrence_resource_model
	./recurrence_resource_model > ../outputs/tables/cpp_recurrence_resource_summary.txt

clean:
	rm -f recurrence_resource_model
