.PHONY: run clean

run:
	c++ -O2 -std=c++17 structure_resource_model.cpp -o structure_resource_model
	./structure_resource_model > ../outputs/tables/cpp_structure_resource_summary.txt

clean:
	rm -f structure_resource_model
