.PHONY: run clean

run:
	c++ -O2 -std=c++17 optimization_allocation_model.cpp -o optimization_allocation_model
	./optimization_allocation_model > ../outputs/tables/cpp_optimization_allocation_summary.txt

clean:
	rm -f optimization_allocation_model
