args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("^--file=", args, value = TRUE)
article_root <- if (length(file_arg) > 0) normalizePath(file.path(dirname(normalizePath(sub("^--file=", "", file_arg[1]), mustWork=TRUE)), ".."), mustWork=TRUE) else getwd()
tables_dir <- file.path(article_root, "outputs", "tables")
figures_dir <- file.path(article_root, "outputs", "figures")
dir.create(tables_dir, recursive=TRUE, showWarnings=FALSE); dir.create(figures_dir, recursive=TRUE, showWarnings=FALSE)
summary_path <- file.path(tables_dir, "component_scenario_summary.csv")
if (!file.exists(summary_path)) stop("Missing component_scenario_summary.csv. Run make python first.")
summary_data <- read.csv(summary_path, stringsAsFactors=FALSE)
summary_data$constraint_review <- ifelse(summary_data$shortage_periods > 0 | summary_data$overflow_periods > 0, "constraint active or failure mode visible", "no shortage or overflow under scenario")
write.csv(summary_data, file.path(tables_dir, "r_constraint_diagnostic_summary.csv"), row.names=FALSE)
component_path <- file.path(tables_dir, "component_register.csv")
if (file.exists(component_path)) {
  components <- read.csv(component_path, stringsAsFactors=FALSE)
  components$priority <- ifelse(components$component_risk_score >= 8, "high", ifelse(components$component_risk_score >= 6, "medium", "low"))
  write.csv(components, file.path(tables_dir, "r_component_review_queue.csv"), row.names=FALSE)
}
png(file.path(figures_dir, "r_shortage_by_component_scenario.png"), width=1100, height=720)
barplot(height=summary_data$total_shortage, names.arg=summary_data$scenario, las=2, ylab="Total shortage", main="Constraint Diagnostics Across Component Scenarios")
grid(); dev.off(); print(summary_data)
