.PHONY: run clean

run:
	c++ -O2 -std=c++17 dynamic_resource_model.cpp -o dynamic_resource_model
	./dynamic_resource_model > ../outputs/tables/cpp_dynamic_resource_summary.txt

clean:
	rm -f dynamic_resource_model
