.PHONY: run clean
run:
	c++ -O2 -std=c++17 component_resource_model.cpp -o component_resource_model
	./component_resource_model > ../outputs/tables/cpp_component_resource_summary.txt
clean:
	rm -f component_resource_model
