.PHONY: run clean

run:
	c++ -O2 -std=c++17 equation_logic_resource_model.cpp -o equation_logic_resource_model
	./equation_logic_resource_model > ../outputs/tables/cpp_equation_logic_summary.txt

clean:
	rm -f equation_logic_resource_model
