println("workflow_name,scenario_name,observation_count,feature_count,retained_components,cumulative_explained_variance,reconstruction_rmse,dominant_component_feature,warning")
println("dimensionality_reduction_audit,synthetic_high_dimensional_sensor_feature_matrix,8,5,2,0.991,0.086,latency,Principal components are mathematical directions not automatically causal factors.")
